---
- name: Configure Amazon Linux EC2 instance for Dockerized app
  hosts: amazonlinux
  become: yes
  vars:
    ghcr_username: "veector40"
    ghcr_image: "ghcr.io/veector40/mi-rest-servicio:latest"

  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user | default('ec2-user') }}"
        groups: docker
        append: yes

    - name: Login to GHCR
      shell: docker login ghcr.io -u {{ ghcr_username }} -p {{ ghcr_pat }}

    - name: Pull Docker image from GHCR
      shell: docker pull {{ ghcr_image }}

    - name: Run Docker container
      shell: |
        # Stop existing container if running
        docker ps --filter "ancestor={{ ghcr_image }}" --format "{{'{{.ID}}'}}" | xargs -r docker stop
        # Remove existing container if it exists
        docker ps -a --filter "ancestor={{ ghcr_image }}" --format "{{'{{.ID}}'}}" | xargs -r docker rm
        # Run the new container
        docker run -d -p 80:80 {{ ghcr_image }}
